"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

// Supported languages
export const SUPPORTED_LANGUAGES = {
  pt: { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  en: { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
} as const;

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;
export type Language = (typeof SUPPORTED_LANGUAGES)[LanguageCode];

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  getLanguageInfo: () => Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("pt"); // Default to Portuguese
  const [mounted, setMounted] = useState(false);

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem(
      "finance-planner-language"
    ) as LanguageCode;
    if (savedLanguage && SUPPORTED_LANGUAGES[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
    setMounted(true);
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    if (!mounted) return;
    localStorage.setItem("finance-planner-language", language);
  }, [language, mounted]);

  const setLanguage = (newLanguage: LanguageCode) => {
    setLanguageState(newLanguage);
  };

  const getLanguageInfo = (): Language => {
    return SUPPORTED_LANGUAGES[language];
  };

  // Translation function
  const t = (key: string, params?: Record<string, string | number>): string => {
    const translations = getTranslations(language);
    let translation = translations[key] || key;

    // Replace parameters in translation
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(`{{${paramKey}}}`, String(value));
      });
    }

    return translation;
  };

  const value = {
    language,
    setLanguage,
    t,
    getLanguageInfo,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translation data
const translations = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.income": "Income",
    "nav.expenses": "Expenses",
    "nav.goals": "Goals",
    "nav.forecast": "Forecast",
    "nav.goalPlanning": "Goal Planning",
    "nav.importExport": "Import/Export",
    "nav.menu": "Menu",
    "nav.toggleMenu": "Toggle mobile menu",
    "nav.closeMenu": "Close mobile menu",

    // Dashboard
    "dashboard.title": "Finance Planner",
    "dashboard.monthlyIncome": "Monthly Income",
    "dashboard.monthlyExpenses": "Monthly Expenses",
    "dashboard.netIncome": "Net Income",
    "dashboard.goalProgress": "Goal Progress",
    "dashboard.upcomingGoals": "Upcoming Goals",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.subtitle": "Your complete financial overview at a glance",
    "dashboard.startIncome": "Add Income",
    "dashboard.startExpense": "Add Expense",
    "dashboard.annualIncome": "Annual Income",
    "dashboard.annualExpenses": "Annual Expenses",
    "dashboard.annualNet": "Annual Net",
    "dashboard.savingsRate": "Savings Rate",
    "dashboard.monthlyFlow": "Monthly Flow",
    "dashboard.completeProfile.title": "Complete Your Financial Profile",
    "dashboard.completeProfile.desc": "You're missing some key information. Add both income and expenses to get the most accurate insights.",
    "dashboard.completeProfile.addIncome": "Add Income →",
    "dashboard.completeProfile.addExpense": "Add Expenses →",
    "dashboard.tooltip.annualIncome": "Your total projected income for the year, including all income sources and frequencies",
    "dashboard.tooltip.annualExpenses": "Your total projected expenses for the year, including recurring bills, installments, and one-time expenses",
    "dashboard.tooltip.annualNet": "Your annual income minus expenses. This is what you have available for savings and investments",
    "dashboard.tooltip.monthlyFlow": "Average monthly cash flow (income minus expenses). Positive means surplus, negative means deficit",
    "dashboard.savingsTarget": "Aim for 20%+ savings rate",
    "dashboard.flow.positive": "✅ Positive cash flow",
    "dashboard.flow.tight": "⚠️ Tight cash flow",
    "dashboard.flow.negative": "🚨 Negative cash flow",
    "dashboard.startIncomeHelper": "💡 Start by adding your income sources to see your annual projection",
    "dashboard.startExpenseHelper": "💡 Add your expenses to track your annual spending patterns",

    // Welcome
    "welcome.title": "Welcome to Your Financial Journey!",
    "welcome.subtitle": "Let's get you started with a few simple steps to unlock the full power of your financial planner",
    "welcome.income.title": "1. Add Your Income",
    "welcome.income.desc": "Start by adding all your income sources - salary, freelance work, investments, or any other regular income.",
    "welcome.income.button": "Add Income",
    "welcome.expense.title": "2. Track Your Expenses",
    "welcome.expense.desc": "Add your monthly expenses like rent, utilities, groceries, and subscriptions to get a complete picture.",
    "welcome.expense.button": "Add Expenses",
    "welcome.goal.title": "3. Set Your Goals",
    "welcome.goal.desc": "Define your financial goals like emergency fund, vacation, or retirement to stay motivated and focused.",
    "welcome.goal.button": "Set Goals",
    "welcome.next.title": "What happens next?",
    "welcome.next.1": "Your dashboard will show detailed financial analytics and insights",
    "welcome.next.2": "Get personalized suggestions to improve your financial health",
    "welcome.next.3": "View forecasts and track your progress toward goals",
    "welcome.next.4": "Export your data or get AI-powered financial analysis",

    // Common
    "common.amount": "Amount",
    "common.name": "Name",
    "common.category": "Category",
    "common.priority": "Priority",
    "common.status": "Status",
    "common.calculated": "Calculated",
    "common.perMonth": "per month",
    "common.startDate": "Start Date",
    "common.type": "Type",
    "common.notSet": "Not set",
    "common.active": "Active",
    "common.inactive": "Inactive",

    // Categories
    "common.category.housing": "Housing",
    "common.category.transportation": "Transportation",
    "common.category.food": "Food",
    "common.category.utilities": "Utilities",
    "common.category.insurance": "Insurance",
    "common.category.healthcare": "Healthcare",
    "common.category.entertainment": "Entertainment",
    "common.category.personal_care": "Personal Care",
    "common.category.education": "Education",
    "common.category.debt_payments": "Debt Payments",
    "common.category.savings": "Savings",
    "common.category.travel": "Travel",
    "common.category.shopping": "Shopping",
    "common.category.kids": "Kids",
    "common.category.miscellaneous": "Miscellaneous",

    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.saving": "Saving...",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.date": "Date",
    "common.description": "Description",
    "common.total": "Total",
    "common.actions": "Actions",

    // Goals
    "goals.targetAmount": "Target Amount",
    "goals.currentAmount": "Current Amount",
    "goals.targetDate": "Target Date",
    "goals.progress": "Progress",
    "goals.addGoal": "Add New Goal",
    "goals.editGoal": "Edit Goal",
    "goals.deleteGoal": "Delete Goal",
    "goals.noGoals": "No goals found. Add a goal to get started.",
    "goals.pageTitle": "Financial Goals",
    "goals.pageSubtitle": "Set, track, and achieve your financial objectives",
    "goals.overallProgress": "Overall Progress",
    "goals.totalGoals": "Total Goals",
    "goals.currentProgress": "Current Progress",
    "goals.activeGoals": "Active Goals",
    "goals.startHelper": "Start by adding your first financial goal to track your progress",
    "goals.form.name": "Goal Name",
    "goals.form.targetAmount": "Target Amount (THB)",
    "goals.form.currentAmount": "Current Amount (THB)",
    "goals.form.priority": "Priority",
    "goals.form.priorityOrder": "Priority Order",
    "goals.form.priorityOrderHelp": "Lower numbers get higher priority for surplus allocation",
    "goals.form.goalType": "Goal Type",
    "goals.form.goalTypeFixed": "Fixed Amount",
    "goals.form.goalTypeOpen": "Open-Ended",
    "goals.form.goalTypeHelp": "Fixed amount goals stop receiving allocation once target is reached",
    "goals.current": "Current",
    "goals.target": "Target",
    "goals.remaining": "Remaining",
    "goals.completionForecast": "Completion Forecast",
    "goals.sort.targetDate": "Sort by Target Date",
    "goals.sort.name": "Sort by Name",
    "goals.sort.progress": "Sort by Progress",

    "goals.sort.priority": "Sort by Priority",
    "goals.form.addTitle": "Add New Goal",
    "goals.form.editTitle": "Edit Goal",
    "goals.form.targetDate": "Target Date",

    "goals.card.remaining": "Remaining",
    "goals.card.targetDate": "Target Date",
    "goals.card.overdue": "{{days}} days overdue",
    "goals.card.daysLeft": "{{days}} days left",
    "goals.card.forecastTitle": "📊 Forecast & Allocation",
    "goals.card.goalType": "Goal Type",
    "goals.card.priorityOrder": "Priority Order",
    "goals.card.monthlyAllocation": "Monthly Allocation",
    "goals.card.estCompletion": "Est. Completion",
    "goals.card.onTrack": "On Track",
    "goals.card.behindSchedule": "Behind Schedule",
    "goals.card.edit": "Edit goal",
    "goals.card.delete": "Delete goal",

    "goals.category.EMERGENCY_FUND": "Emergency Fund",
    "goals.category.RETIREMENT": "Retirement",
    "goals.category.EDUCATION": "Education",
    "goals.category.HOME_PURCHASE": "Home Purchase",
    "goals.category.VACATION": "Vacation",
    "goals.category.DEBT_PAYOFF": "Debt Payoff",
    "goals.category.MAJOR_PURCHASE": "Major Purchase",
    "goals.category.INVESTMENT": "Investment",
    "goals.category.OTHER": "Other",
    "goals.category.emergency_fund": "Emergency Fund",
    "goals.category.retirement": "Retirement",
    "goals.category.education": "Education",
    "goals.category.home_purchase": "Home Purchase",
    "goals.category.vacation": "Vacation",
    "goals.category.debt_payoff": "Debt Payoff",
    "goals.category.major_purchase": "Major Purchase",
    "goals.category.investment": "Investment",
    "goals.category.other": "Other",

    "common.priority.LOW": "Low",
    "common.priority.MEDIUM": "Medium",
    "common.priority.HIGH": "High",
    "common.priority.CRITICAL": "Critical",
    "common.priority.low": "Low",
    "common.priority.medium": "Medium",
    "common.priority.high": "High",
    "common.priority.critical": "Critical",

    // Income
    "income.title": "Income",
    "income.addIncome": "Add New Income",
    "income.editIncome": "Edit Income",
    "income.deleteIncome": "Delete Income",
    "income.deleteConfirm": "Are you sure you want to delete this income source?",
    "income.noIncome": "No income found. Add an income source to get started.",
    "income.totalIncome": "Total Income",
    "income.pageTitle": "Income Management",
    "income.pageSubtitle": "Manage your income sources and track your earning potential",
    "income.totalMonthly": "Total Monthly Income",
    "income.activeSources": "active sources",
    "income.listTitle": "Income Sources",
    "income.addButton": "Add Income Source",
    "income.form.addTitle": "Add New Income Source",
    "income.form.editTitle": "Edit Income Source",
    "income.form.name": "Income Name",
    "income.form.amount": "Amount (THB)",
    "income.form.frequency": "Frequency",
    "income.form.startDate": "Start Date",
    "income.form.endDate": "End Date",
    "income.form.leaveEmpty": "Leave empty for ongoing income",
    "income.form.description": "Description",
    "income.form.active": "Active income source",
    "income.form.placeholder.name": "e.g., Salary, Freelance, Investment",
    "income.form.placeholder.description": "Additional details about this income source...",
    "income.editing": "Currently editing this income source",
    "income.monthlyEquivalent": "Monthly Equivalent",
    "income.list.ongoing": "Ongoing",
    "income.summary.from": "from {{count}}",

    // Expenses
    "expenses.title": "Expenses",
    "expenses.addExpense": "Add New Expense",
    "expenses.editExpense": "Edit Expense",
    "expenses.deleteExpense": "Delete Expense",
    "expenses.deleteConfirm": "Are you sure you want to delete this expense?",
    "expenses.noExpenses": "No expenses found. Add an expense to get started.",
    "expenses.totalExpenses": "Total Expenses",
    "expenses.pageTitle": "Expense Tracking",
    "expenses.pageSubtitle": "Track your spending, categorize expenses, and manage your budget",
    "expenses.totalMonthly": "Total Monthly Expenses",
    "expenses.activeExpenses": "active expenses",
    "expenses.listTitle": "Expenses",
    "expenses.addButton": "Add Expense",
    "expenses.form.addTitle": "Add New Expense",
    "expenses.form.editTitle": "Edit Expense",
    "expenses.form.name": "Expense Name",
    "expenses.form.amount": "Amount (THB)",
    "expenses.form.category": "Category",
    "expenses.form.dueDate": "Due Date",
    "expenses.form.priority": "Priority",
    "expenses.form.recurring": "Recurring expense",
    "expenses.form.frequency": "Frequency",
    "expenses.form.interval": "Every X Weeks",
    "expenses.form.intervalHelp": "Set how often this expense repeats (e.g., every 2 weeks, every 3 weeks)",
    "expenses.form.installment": "Pay in installments",
    "expenses.form.installmentMonths": "Number of Months",
    "expenses.stats.total": "Total Expenses",
    "expenses.stats.recurring": "Recurring",
    "expenses.stats.categories": "Categories",
    "expenses.stats.yearly": "Yearly Total",
    "expenses.controls.view.calendar": "Calendar",
    "expenses.controls.view.list": "List",
    "expenses.controls.filter.all": "All Categories",
    "expenses.form.placeholder.name": "e.g., Rent, Groceries, Gas",
    "expenses.form.paymentMethod": "Payment Method",
    "expenses.form.paymentMethod.pix": "PIX",
    "expenses.form.paymentMethod.credit_card": "Credit Card",
    "expenses.form.paymentMethod.debit_card": "Debit Card",
    "expenses.form.paymentMethod.cash": "Cash",
    "expenses.form.creditCardAccount": "Credit Card Account",
    "expenses.form.creditCardAccount.inter": "Inter",
    "expenses.form.creditCardAccount.xp": "XP",
    "expenses.form.purchaseDate": "Purchase Date",
    "expenses.form.purchaseDateHelper": "When did you make this purchase?",
    "expenses.form.autoCalculatedDue": "Due date calculated based on card closing date.",
    "expenses.list.active": "Active expense",
    "expenses.legend": "Expense Type Legend:",
    "expenses.type.oneTime": "One-time expenses",
    "expenses.type.recurring": "Recurring expenses",
    "expenses.type.installment": "Installment expenses",
    "expenses.type.oneTimeLabel": "One-time",
    "expenses.type.recurringLabel": "Recurring",
    "expenses.type.installmentLabel": "Installment ({{months}} months)",
    "expenses.noExpensesMonth": "No expenses this month",
    "expenses.monthlyEquivalent": "Monthly Equivalent",

    // Forecast
    "forecast.title": "Financial Forecast",
    "forecast.projection": "Financial Projection",
    "forecast.months": "Months to Forecast",
    "forecast.startingBalance": "Starting Balance",
    "forecast.projectedBalance": "Projected Balance",
    "forecast.chart": "Forecast Chart",
    "forecast.pageTitle": "Financial Forecast",
    "forecast.pageSubtitle": "Financial projections based on your current income, expenses, and goals. Choose your start date and forecast period.",
    "forecast.period": "Forecast period",
    "forecast.recalculating": "Recalculating...",
    "forecast.forecastPeriod": "Forecast Period",
    "forecast.conservativeMode": "Conservative Mode",
    "forecast.includeGoals": "Include Goals",
    "forecast.reset": "Reset",
    "forecast.recalculate": "Recalculate",
    "forecast.resetAll": "Reset All",
    "forecast.now": "Now",
    "forecast.finalBalance": "Final Balance",
    "forecast.totalIncome": "Total Income",
    "forecast.totalExpenses": "Total Expenses",
    "forecast.totalGoalContributions": "Goal Contributions",
    "forecast.afterMonths": "After {{months}} months",
    "forecast.avgMonth": "Avg: {{amount}}/month",
    "forecast.towardGoals": "Toward your goals",
    "forecast.details": "Forecast Details",
    "forecast.view.table": "Table View",
    "forecast.view.chart": "Chart View",
    "forecast.view.goals": "Goal Progress",
    "forecast.view.calendar": "Calendar View",
    "forecast.table.month": "Month",
    "forecast.table.income": "Income",
    "forecast.table.expenses": "Expenses",
    "forecast.table.goals": "Goals",
    "forecast.table.netChange": "Net Change",
    "forecast.table.endingBalance": "Ending Balance",
    "forecast.chart.title": "Balance Trend",
    "forecast.chart.low": "Low",
    "forecast.chart.avgNet": "Avg Net",
    "forecast.chart.high": "High",
    "forecast.chart.legend.positive": "Positive Balance",
    "forecast.chart.legend.negative": "Negative Balance",
    "forecast.chart.legend.zero": "Zero Line",
    "forecast.goals.title": "Goal Progress Projections",
    "forecast.goals.progressText": "{{current}} of {{target}}",
    "forecast.goals.onTrack": "On Track",
    "forecast.goals.behind": "Behind Schedule",
    "forecast.goals.estimatedCompletion": "Estimated completion",
    "forecast.goals.noActive": "No active goals to track",
    "forecast.calendar.title": "Monthly Forecast Calendar",
    "forecast.calendar.viewDetails": "View Details",
    "forecast.calendar.items": "items",
    "forecast.calendar.noData": "No forecast data available. Configure your forecast settings above.",
    "forecast.warning.cashFlow": "Cash Flow Warning",
    "forecast.warning.negativeBalance": "Your forecast shows {{months}} months with negative balance. Consider adjusting your expenses or increasing income.",
    "forecast.resetModal.title": "Reset Forecast Configuration",
    "forecast.resetModal.content": "Are you sure you want to reset all forecast settings to defaults? This will restore starting balance to current balance, reset start date to current month, and restore other settings to their default values.",
    "forecast.resetModal.resetting": "Resetting...",
    "forecast.title.resetCurrent": "Reset to current balance",
    "forecast.title.recalculate": "Recalculate forecast",
    "forecast.title.resetAll": "Reset all forecast settings to defaults",
    "forecast.title.selectStart": "Select forecast start month",
    "forecast.title.resetMonth": "Reset to current month",
    "forecast.title.netChange": "Net change: {{amount}}",

    // Import/Export
    "importExport.title": "Import / Export Data",
    "importExport.exportDescription": "Download your financial data as a JSON file.",
    "importExport.importDescription": "Upload a previously exported JSON file to restore your data.",
    "importExport.exportButton": "Export Data",
    "importExport.importButton": "Import Data",
    "importExport.success": "Data imported successfully!",
    "importExport.error": "Error importing data. Please check the file format.",

    // AI
    "ai.askAdvisor": "Ask AI Advisor",
    "ai.analyzing": "Analyzing your finances...",
    "ai.suggestion": "Suggestion",
    "ai.insight": "Insight",
    "ai.button.assistant": "AI Assistant",
    "ai.button.ask": "Ask AI",
    "ai.button.setup": "Setup AI",
    "ai.setup.title": "AI Features Not Configured",
    "ai.setup.desc": "To use AI-powered financial analysis, you need to set up your API keys.",
    "ai.setup.instructions": "Setup Instructions:",
    "ai.mode.prompt.title": "Copy & Paste Mode",
    "ai.mode.prompt.desc": "We'll generate optimized prompts that you can copy and paste into your favorite AI assistant (ChatGPT, Claude, Gemini, etc.) for personalized financial advice.",
    "ai.tab.quick": "⚡ Quick Analysis",
    "ai.tab.custom": "💭 Custom Question",
    "ai.custom.label": "Ask your financial question",
    "ai.custom.placeholder": "e.g., 'Should I prioritize paying off debt or saving for retirement?' or 'How can I afford my dream vacation in 2 years?'",
    "ai.custom.button.generate": "Generate Prompt",
    "ai.custom.button.analyze": "Get AI Analysis",
    "ai.result.nextSteps": "Next Steps",
    "ai.result.failed": "Analysis Failed",
    "ai.result.tryAgain": "Try Again",
    "ai.model": "AI Model",
    "ai.modal.title.prompt": "AI Financial Assistant",
    "ai.modal.title.advisor": "AI Financial Advisor",
    "ai.modal.subtitle.prompt": "Generate prompts for your favorite AI assistant",
    "ai.modal.subtitle.advisor": "Get personalized insights about your finances",
    "ai.footer.prompt": "📋 Your data stays private - prompts are generated locally",
    "ai.footer.api": "🔒 Your financial data is analyzed securely and privately",
    "ai.close": "Close",
    "ai.clear": "Clear",
    "ai.generatedPrompt": "Generated Prompt",
    "ai.copied": "Copied!",
    "ai.copy": "Copy Prompt",
    "ai.howToUse": "How to use this prompt:",
    "ai.step1": "Copy the prompt above using the \"Copy Prompt\" button",
    "ai.step2": "Open your favorite AI assistant (ChatGPT, Claude, Gemini, etc.)",
    "ai.step3": "Paste the prompt and send it",
    "ai.step4": "Get personalized financial advice based on your actual data!",


    // Theme
    "theme.toggle.light": "Switch to light mode",
    "theme.toggle.dark": "Switch to dark mode",

    // Charts - Expenses
    "charts.expenses.title": "Expense Category Breakdown",
    "charts.expenses.subtitle": "Analyze your spending distribution across categories",
    "charts.expenses.includeInactive": "Include Inactive",
    "charts.expenses.view.pie": "Pie",
    "charts.expenses.view.donut": "Donut",
    "charts.expenses.view.bar": "Bar",
    "charts.expenses.view.treemap": "Tree",
    "charts.expenses.categories": "Categories",
    "charts.expenses.count": "expenses",
    "charts.expenses.details": "Details",
    "charts.expenses.original": "Original",
    "charts.expenses.monthly": "Monthly",
    "charts.expenses.totalMonthly": "Total Monthly",
    "charts.expenses.totalExpenses": "Total Expenses",
    "charts.expenses.avgPerCategory": "Avg per Category",
    "charts.expenses.noData.title": "No Expenses Yet",
    "charts.expenses.noData.desc": "Add some expenses to see your category breakdown",
    "charts.expenses.help": "💡 Click on chart segments or category list to drill down • Switch views to see different perspectives",

    // Charts - Goals
    "charts.goals.title": "Goal Progress Tracking",
    "charts.goals.subtitle": "Monitor your financial goals and completion forecasts",
    "charts.goals.activeOnly": "Active Only",
    "charts.goals.view.progress": "Progress",
    "charts.goals.view.timeline": "Timeline",
    "charts.goals.view.allocation": "Allocation",
    "charts.goals.totalGoals": "Total Goals",
    "charts.goals.onTrack": "On Track",
    "charts.goals.totalSaved": "Total Saved",
    "charts.goals.monthlyAllocation": "Monthly Allocation",
    "charts.goals.noData.title": "No Goals Yet",
    "charts.goals.noData.desc": "Create your first financial goal to see progress tracking",
    "charts.goals.help": "💡 Click on goals for detailed information • Use view modes to see different perspectives",
    "charts.goals.status.onTrack": "On Track",
    "charts.goals.status.behind": "Behind Schedule",
    "charts.goals.tooltip.progress": "Progress",
    "charts.goals.tooltip.current": "Current",
    "charts.goals.tooltip.target": "Target",
    "charts.goals.tooltip.remaining": "Remaining",
    "charts.goals.tooltip.status": "Status",
    "charts.goals.tooltip.completion": "Completion",

    // Charts - Income vs Expenses
    "charts.incomeVsExpenses.title": "Income vs Expenses Trend",
    "charts.incomeVsExpenses.subtitle": "Track your financial flow over time",
    "charts.incomeVsExpenses.period": "Period",
    "charts.incomeVsExpenses.showProjection": "Show Projection",
    "charts.incomeVsExpenses.months": "Months",
    "charts.incomeVsExpenses.avgIncome": "Avg Monthly Income",
    "charts.incomeVsExpenses.avgExpenses": "Avg Monthly Expenses",
    "charts.incomeVsExpenses.avgNet": "Avg Net Income",
    "charts.incomeVsExpenses.help": "💡 Click on legend items to focus on specific lines • Hover over data points for details",
    "charts.incomeVsExpenses.series.income": "Income",
    "charts.incomeVsExpenses.series.expenses": "Expenses",
    "charts.incomeVsExpenses.series.netIncome": "Net Income",
    "charts.incomeVsExpenses.tooltip.income": "Income",
    "charts.incomeVsExpenses.tooltip.expenses": "Expenses",
    "charts.incomeVsExpenses.tooltip.net": "Net",
    "charts.incomeVsExpenses.tooltip.surplus": "Surplus",
    "charts.incomeVsExpenses.tooltip.deficit": "Deficit",

    // Frequency
    "frequency.daily": "Daily",
    "frequency.weekly": "Weekly",
    "frequency.biweekly": "Bi-weekly",
    "frequency.monthly": "Monthly",
    "frequency.quarterly": "Quarterly",
    "frequency.yearly": "Yearly",
    "frequency.one_time": "One-time",


    // Currencies
    "currency.selector.title": "Select Currency",
    "currency.selector.label": "Select currency",
    "currency.selector.buttonTitle": "Current currency: {{name}}",

    // Languages
    "language.selector.title": "Select Language",
    "language.selector.label": "Select language",

    // Months
    "month.january": "January",
    "month.february": "February",
    "month.march": "March",
    "month.april": "April",
    "month.may": "May",
    "month.june": "June",
    "month.july": "July",
    "month.august": "August",
    "month.september": "September",
    "month.october": "October",
    "month.november": "November",
    "month.december": "December",
    "goalPlan.title": "Goal Planning",
    "goalPlan.subtitle": "Plan and track your monthly goal allocations with detailed projections and insights",
    "goalPlan.summary.totalSuggestions": "Total Suggestions",
    "goalPlan.summary.potentialImpact": "Potential Impact",
    "goalPlan.summary.perMonth": "Per month if all implemented",
    "goalPlan.summary.actionableItems": "Actionable Items",
    "goalPlan.schedule.title": "Monthly Goal Allocation Schedule",
    "goalPlan.schedule.subtitle": "Detailed month-by-month breakdown of recommended goal allocations based on your financial forecast",
    "goalPlan.schedule.showAllocation": "Show Allocation",
    "goalPlan.schedule.export": "Export CSV",
    "goalPlan.schedule.view.calendar": "Calendar",
    "goalPlan.schedule.view.table": "Table",
    "goalPlan.schedule.view.chart": "Chart",
    "goalPlan.stats.monthlyAvg": "Total Monthly Avg",
    "goalPlan.stats.onTrack": "Goals On Track",
    "goalPlan.stats.surplusMonths": "Months with Surplus",
    "goalPlan.stats.peakAllocation": "Peak Allocation",
    "goalPlan.empty.title": "No Goals Yet",
    "goalPlan.empty.desc": "Add some financial goals to see your personalized monthly allocation schedule",
    "goalPlan.empty.button": "Add Goals",
    "goalPlan.calendar.total": "Total: {{amount}}",
    "goalPlan.calendar.surplus": "{{amount}} surplus available",
    "goalPlan.calendar.surplusRemaining": "{{amount}} remaining surplus",
    "goalPlan.calendar.noAllocations": "No allocations",
    "goalPlan.table.month": "Month",
    "goalPlan.table.allocations": "Goal Allocations",
    "goalPlan.table.total": "Total Allocation",
    "goalPlan.table.surplus": "Remaining Surplus",
    "goalPlan.table.guidance": "Guidance",
    "goalPlan.table.goalsFunded": "Goals funded",
    "goalPlan.table.surplusAvailable": "Surplus available",
    "goalPlan.table.noSurplus": "No surplus",
    "goalPlan.chart.trends": "Monthly Allocation Trends",
    "goalPlan.chart.legend.allocations": "Goal Allocations",
    "goalPlan.chart.legend.surplus": "Available Surplus",
    "goalPlan.chart.distribution": "Goal Progress Distribution",
    "goalPlan.chart.openEnded": "Open-ended • {{amount}}",
    "goalPlan.projections.title": "Goal Progress Projections",
    "goalPlan.projections.subtitle": "See how your goals will progress based on current allocation plan",
    "goalPlan.projections.forecastPeriod": "Forecast Period",
    "goalPlan.projections.months": "{{count}} months",
    "goalPlan.projections.current": "Current:",
    "goalPlan.projections.projected": "Projected:",
    "goalPlan.projections.target": "Target:",
    "goalPlan.projections.willComplete": "Will Complete",
    "goalPlan.projections.onTrack": "On Track",
    "goalPlan.projections.behind": "Behind Schedule",
    "goalPlan.projections.projectedLabel": "{{percent}} projected",
    "goalPlan.projections.monthlyAllocation": "Monthly Allocation",
    "goalPlan.projections.estimatedCompletion": "Estimated Completion",
    "goalPlan.projections.notDetermined": "Not determined",
    "goalPlan.projections.remainingAmount": "Remaining Amount",
    "goalPlan.projections.warning": "This goal may not reach the target on time.",
    "goalPlan.projections.warningDesc": "Consider increasing the monthly allocation or adjusting the target date.",
    "goalPlan.projections.success": "This goal will be completed within the forecast period!",
    "goalPlan.projections.summary.onTrack": "Goals On Track",
    "goalPlan.projections.summary.willComplete": "Will Complete",
    "goalPlan.projections.summary.totalAllocation": "Total Monthly Allocation",
    "goalPlan.tools.title": "Goal Planning Tools",
    "goalPlan.tools.subtitle": "Experiment with different allocation scenarios and get optimization suggestions",
    "goalPlan.optimizer.title": "Smart Allocation Optimizer",
    "goalPlan.optimizer.current": "Current Allocation",
    "goalPlan.optimizer.suggestions": "Optimization Suggestions",
    "goalPlan.optimizer.rebalance.title": "Rebalance Allocations",
    "goalPlan.optimizer.rebalance.desc": "Consider reducing allocation to {{early}} and increasing {{late}}",
    "goalPlan.optimizer.rebalance.impact": "Could improve overall completion timeline",
    "goalPlan.optimizer.surplus.title": "Use Available Surplus",
    "goalPlan.optimizer.surplus.desc": "You have {{amount}} in surplus that could accelerate goal completion",
    "goalPlan.optimizer.surplus.impact": "Could bring behind-schedule goals back on track",
    "goalPlan.optimizer.timeline.title": "Timeline Optimization",
    "goalPlan.optimizer.timeline.desc": "Consider adjusting goal deadlines to create more balanced monthly allocations",
    "goalPlan.optimizer.timeline.impact": "Could reduce peak allocation months and improve cash flow",
    "goalPlan.scenarios.title": "What-If Scenarios",
    "goalPlan.scenarios.budget.title": "+20% Budget",
    "goalPlan.scenarios.budget.desc": "What if you increased monthly savings by 20%?",
    "goalPlan.scenarios.budget.newAvg": "New monthly avg:",
    "goalPlan.scenarios.budget.reduction": "Estimated time reduction:",
    "goalPlan.scenarios.budget.impact": "Goals could complete {{speed}} faster",
    "goalPlan.scenarios.budget.impactHigh": "significantly",
    "goalPlan.scenarios.budget.impactMod": "moderately",
    "goalPlan.scenarios.extension.title": "+6 Month Extension",
    "goalPlan.scenarios.extension.desc": "What if you extended goal deadlines by 6 months?",
    "goalPlan.scenarios.extension.reduced": "Reduced monthly:",
    "goalPlan.scenarios.extension.savings": "Monthly savings:",
    "goalPlan.scenarios.extension.impact": "More breathing room in monthly budget",
    "goalPlan.scenarios.priority.title": "Priority Reorder",
    "goalPlan.scenarios.priority.desc": "What if you focused on highest priority goals first?",
    "goalPlan.scenarios.priority.highGoals": "High priority goals:",
    "goalPlan.scenarios.priority.strategy": "Focus strategy:",
    "goalPlan.scenarios.priority.strategyVal": "Sequential completion",
    "goalPlan.scenarios.priority.impact": "Complete important goals faster, others later",
    "goalPlan.quickActions.title": "Quick Planning Actions",
    "goalPlan.quickActions.export": "Export Plan",
    "goalPlan.quickActions.exportDesc": "Download your complete allocation schedule",
    "goalPlan.quickActions.adjust": "Adjust Goals",
    "goalPlan.quickActions.adjustDesc": "Modify targets, deadlines, or priorities",
    "goalPlan.quickActions.settings": "Forecast Settings",
    "goalPlan.quickActions.settingsDesc": "Adjust forecast timeline and parameters",
    "goalPlan.quickActions.backup": "Backup Plan",
    "goalPlan.quickActions.backupDesc": "Save or restore your financial plan",
    "goalPlan.tips.title": "How to Use These Suggestions",
    "goalPlan.tips.priority": "Priority Levels",
    "goalPlan.tips.priority.critical": "Critical: Address immediately to avoid financial stress",
    "goalPlan.tips.priority.high": "High: Important for long-term financial health",
    "goalPlan.tips.priority.medium": "Medium: Good opportunities for improvement",
    "goalPlan.tips.priority.low": "Low: Nice-to-have optimizations",
    "goalPlan.tips.categories": "Categories",
    "goalPlan.tips.categories.income": "Income: Ways to increase your earnings",
    "goalPlan.tips.categories.expense": "Expense: Opportunities to reduce spending",
    "goalPlan.tips.categories.goal": "Goal: Help with achieving financial objectives",
    "goalPlan.tips.categories.general": "General: Overall financial health improvements",
  },
  pt: {
    // Navigation
    "nav.dashboard": "Painel",
    "nav.income": "Renda",
    "nav.expenses": "Despesas",
    "nav.goals": "Metas",
    "nav.forecast": "Previsão",
    "nav.goalPlanning": "Planejamento de Metas",
    "nav.importExport": "Importar/Exportar",
    "nav.menu": "Menu",
    "nav.toggleMenu": "Alternar menu móvel",
    "nav.closeMenu": "Fechar menu móvel",

    // Dashboard
    "dashboard.title": "Planejador Financeiro",
    "dashboard.subtitle": "Sua visão financeira completa num relance",
    "dashboard.monthlyIncome": "Renda Mensal",
    "dashboard.monthlyExpenses": "Despesas Mensais",
    "dashboard.netIncome": "Renda Líquida",
    "dashboard.goalProgress": "Progresso das Metas",
    "dashboard.upcomingGoals": "Próximas Metas",
    "dashboard.quickActions": "Ações Rápidas",
    "dashboard.startIncome": "Adicionar Renda",
    "dashboard.startExpense": "Adicionar Despesa",
    "dashboard.annualIncome": "Renda Anual",
    "dashboard.annualExpenses": "Despesas Anuais",
    "dashboard.annualNet": "Saldo Anual",
    "dashboard.savingsRate": "Taxa de Poupança",
    "dashboard.monthlyFlow": "Fluxo Mensal",
    "dashboard.completeProfile.title": "Complete seu Perfil Financeiro",
    "dashboard.completeProfile.desc": "Estão faltando algumas informações importantes. Adicione renda e despesas para obter insights mais precisos.",
    "dashboard.completeProfile.addIncome": "Adicionar Renda →",
    "dashboard.completeProfile.addExpense": "Adicionar Despesas →",
    "dashboard.tooltip.annualIncome": "Sua renda total projetada para o ano, incluindo todas as fontes e frequências.",
    "dashboard.tooltip.annualExpenses": "Suas despesas totais projetadas para o ano, incluindo contas recorrentes, parcelas e despesas únicas.",
    "dashboard.tooltip.annualNet": "Sua renda anual menos despesas. É o que você tem disponível para poupança e investimentos.",
    "dashboard.tooltip.monthlyFlow": "Fluxo de caixa mensal médio (renda menos despesas). Positivo significa superávit, negativo significa déficit.",
    "dashboard.savingsTarget": "Mire em 20%+ de taxa de poupança",
    "dashboard.flow.positive": "✅ Fluxo de caixa positivo",
    "dashboard.flow.tight": "⚠️ Fluxo de caixa apertado",
    "dashboard.flow.negative": "🚨 Fluxo de caixa negativo",
    "dashboard.startIncomeHelper": "💡 Comece adicionando suas fontes de renda para ver sua projeção anual",
    "dashboard.startExpenseHelper": "💡 Adicione suas despesas para acompanhar seus padrões de gastos anuais",

    // Welcome
    "welcome.title": "Bem-vindo à sua Jornada Financeira!",
    "welcome.subtitle": "Vamos começar com alguns passos simples para desbloquear todo o poder do seu planejador financeiro",
    "welcome.income.title": "1. Adicione sua Renda",
    "welcome.income.desc": "Comece adicionando todas as suas fontes de renda - salário, trabalho autônomo, investimentos ou qualquer outra renda regular.",
    "welcome.income.button": "Adicionar Renda",
    "welcome.expense.title": "2. Rastreie suas Despesas",
    "welcome.expense.desc": "Adicione suas despesas mensais como aluguel, serviços públicos, compras e assinaturas para ter uma visão completa.",
    "welcome.expense.button": "Adicionar Despesas",
    "welcome.goal.title": "3. Defina suas Metas",
    "welcome.goal.desc": "Defina suas metas financeiras como fundo de emergência, férias ou aposentadoria para se manter motivado e focado.",
    "welcome.goal.button": "Definir Metas",
    "welcome.next.title": "O que acontece depois?",
    "welcome.next.1": "Seu painel mostrará análises e insights financeiros detalhados",
    "welcome.next.2": "Receba sugestões personalizadas para melhorar sua saúde financeira",
    "welcome.next.3": "Visualize previsões e acompanhe seu progresso em direção às metas",
    "welcome.next.4": "Exporte seus dados ou obtenha análise financeira alimentada por IA",

    // Common
    "common.amount": "Valor",
    "common.name": "Nome",
    "common.category": "Categoria",
    "common.priority": "Prioridade",
    "common.status": "Status",
    "common.calculated": "Calculado",
    "common.perMonth": "por mês",
    "common.startDate": "Data de Início",
    "common.type": "Tipo",
    "common.notSet": "Não definido",
    "common.active": "Ativo",
    "common.inactive": "Inativo",

    // Categories
    "common.category.housing": "Habitação",
    "common.category.transportation": "Transporte",
    "common.category.food": "Alimentação",
    "common.category.utilities": "Contas e Serviços",
    "common.category.insurance": "Seguros",
    "common.category.healthcare": "Saúde",
    "common.category.entertainment": "Lazer",
    "common.category.personal_care": "Cuidados Pessoais",
    "common.category.education": "Educação",
    "common.category.debt_payments": "Dívidas",
    "common.category.savings": "Economias",
    "common.category.travel": "Viagem",
    "common.category.shopping": "Compras",
    "common.category.kids": "Filhos",
    "common.category.miscellaneous": "Diversos",

    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.edit": "Editar",
    "common.delete": "Excluir",
    "common.add": "Adicionar",
    "common.saving": "Salvando...",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.date": "Data",
    "common.description": "Descrição",
    "common.total": "Total",
    "common.actions": "Ações",

    // Goals
    "goals.targetAmount": "Valor Alvo",
    "goals.currentAmount": "Valor Atual",
    "goals.targetDate": "Data Alvo",
    "goals.progress": "Progresso",
    "goals.addGoal": "Adicionar Nova Meta",
    "goals.editGoal": "Editar Meta",
    "goals.deleteGoal": "Excluir Meta",
    "goals.noGoals": "Nenhuma meta encontrada. Adicione uma meta para começar.",
    "goals.pageTitle": "Objetivos Financeiros",
    "goals.pageSubtitle": "Defina, acompanhe e alcance seus objetivos financeiros",
    "goals.overallProgress": "Progresso Geral",
    "goals.totalGoals": "Total de Objetivos",
    "goals.currentProgress": "Progresso Atual",
    "goals.activeGoals": "Objetivos Ativos",
    "goals.startHelper": "Comece adicionando seu primeiro objetivo financeiro para acompanhar seu progresso",
    "goals.form.name": "Nome do Objetivo",
    "goals.form.targetAmount": "Valor Alvo (BRL)",
    "goals.form.currentAmount": "Valor Atual (BRL)",
    "goals.form.priority": "Prioridade",
    "goals.form.priorityOrder": "Ordem de Prioridade",
    "goals.form.priorityOrderHelp": "Números menores têm maior prioridade para alocação de excedente",
    "goals.form.goalType": "Tipo de Objetivo",
    "goals.form.goalTypeFixed": "Valor Fixo",
    "goals.form.goalTypeOpen": "Aberto",
    "goals.form.goalTypeHelp": "Objetivos de valor fixo param de receber alocação quando o alvo é atingido",
    "goals.current": "Atual",
    "goals.target": "Alvo",
    "goals.remaining": "Restante",
    "goals.completionForecast": "Previsão de Conclusão",
    "goals.sort.targetDate": "Ordenar por Data Alvo",
    "goals.sort.name": "Ordenar por Nome",
    "goals.sort.progress": "Ordenar por Progresso",

    "goals.sort.priority": "Ordenar por Prioridade",
    "goals.form.addTitle": "Adicionar Nova Meta",
    "goals.form.editTitle": "Editar Meta",
    "goals.form.targetDate": "Data Alvo",

    "goals.card.remaining": "Restante",
    "goals.card.targetDate": "Data Alvo",
    "goals.card.overdue": "{{days}} dias atrasado",
    "goals.card.daysLeft": "{{days}} dias restantes",
    "goals.card.forecastTitle": "📊 Previsão e Alocação",
    "goals.card.goalType": "Tipo de Objetivo",
    "goals.card.priorityOrder": "Ordem de Prioridade",
    "goals.card.monthlyAllocation": "Alocação Mensal",
    "goals.card.estCompletion": "Conclusão Estimada",
    "goals.card.onTrack": "No Prazo",
    "goals.card.behindSchedule": "Atrasado",
    "goals.card.edit": "Editar meta",
    "goals.card.delete": "Excluir meta",

    "goals.category.EMERGENCY_FUND": "Fundo de Emergência",
    "goals.category.RETIREMENT": "Aposentadoria",
    "goals.category.EDUCATION": "Educação",
    "goals.category.HOME_PURCHASE": "Compra da Casa",
    "goals.category.VACATION": "Férias",
    "goals.category.DEBT_PAYOFF": "Pagamento de Dívidas",
    "goals.category.MAJOR_PURCHASE": "Compra Importante",
    "goals.category.INVESTMENT": "Investimento",
    "goals.category.OTHER": "Outro",
    "goals.category.emergency_fund": "Fundo de Emergência",
    "goals.category.retirement": "Aposentadoria",
    "goals.category.education": "Educação",
    "goals.category.home_purchase": "Compra da Casa",
    "goals.category.vacation": "Férias",
    "goals.category.debt_payoff": "Pagamento de Dívidas",
    "goals.category.major_purchase": "Compra Importante",
    "goals.category.investment": "Investimento",
    "goals.category.other": "Outro",

    "common.priority.LOW": "Baixa",
    "common.priority.MEDIUM": "Média",
    "common.priority.HIGH": "Alta",
    "common.priority.CRITICAL": "Crítica",
    "common.priority.low": "Baixa",
    "common.priority.medium": "Média",
    "common.priority.high": "Alta",
    "common.priority.critical": "Crítica",

    // Income
    "income.title": "Renda",
    "income.addIncome": "Adicionar Nova Renda",
    "income.editIncome": "Editar Renda",
    "income.deleteIncome": "Excluir Renda",
    "income.deleteConfirm": "Tem certeza que deseja excluir esta fonte de renda?",
    "income.noIncome": "Nenhuma renda encontrada. Adicione uma fonte de renda para começar.",
    "income.totalIncome": "Renda Total",
    "income.pageTitle": "Gestão de Renda",
    "income.pageSubtitle": "Gerencie suas fontes de renda e acompanhe seu potencial de ganhos",
    "income.totalMonthly": "Renda Mensal Total",
    "income.activeSources": "fontes ativas",
    "income.listTitle": "Fontes de Renda",
    "income.addButton": "Adicionar Fonte de Renda",
    "income.form.addTitle": "Adicionar Nova Fonte de Renda",
    "income.form.editTitle": "Editar Fonte de Renda",
    "income.form.name": "Nome da Renda",
    "income.form.amount": "Valor (BRL)",
    "income.form.frequency": "Frequência",
    "income.form.startDate": "Data de Início",
    "income.form.endDate": "Data de Término",
    "income.form.leaveEmpty": "Deixe vazio para renda contínua",
    "income.form.description": "Descrição",
    "income.form.active": "Fonte de renda ativa",
    "income.form.placeholder.name": "ex: Salário, Freelance, Investimentos",
    "income.form.placeholder.description": "Detalhes adicionais sobre esta fonte de renda...",
    "income.editing": "Editando esta fonte de renda atualmente",
    "income.monthlyEquivalent": "Equivalente Mensal",
    "income.list.ongoing": "Contínuo",
    "income.summary.from": "de {{count}}",

    // Expenses
    "expenses.title": "Despesas",
    "expenses.addExpense": "Adicionar Nova Despesa",
    "expenses.editExpense": "Editar Despesa",
    "expenses.deleteExpense": "Excluir Despesa",
    "expenses.deleteConfirm": "Tem certeza que deseja excluir esta despesa?",
    "expenses.noExpenses": "Nenhuma despesa encontrada. Adicione uma despesa para começar.",
    "expenses.totalExpenses": "Despesas Totais",
    "expenses.pageTitle": "Rastreamento de Despesas",
    "expenses.pageSubtitle": "Acompanhe seus gastos, categorize despesas e gerencie seu orçamento",
    "expenses.totalMonthly": "Despesas Mensais Totais",
    "expenses.activeExpenses": "despesas ativas",
    "expenses.listTitle": "Despesas",
    "expenses.addButton": "Adicionar Despesa",
    "expenses.form.addTitle": "Adicionar Nova Despesa",
    "expenses.form.editTitle": "Editar Despesa",
    "expenses.form.name": "Nome da Despesa",
    "expenses.form.amount": "Valor (BRL)",
    "expenses.form.category": "Categoria",
    "expenses.form.dueDate": "Data de Vencimento",
    "expenses.form.priority": "Prioridade",
    "expenses.form.recurring": "Despesa recorrente",
    "expenses.form.frequency": "Frequência",
    "expenses.form.interval": "A cada X Semanas",
    "expenses.form.intervalHelp": "Defina a frequência de repetição (ex: a cada 2 semanas)",
    "expenses.form.installment": "Pagar parcelado",
    "expenses.form.installmentMonths": "Número de Meses",
    "expenses.stats.total": "Despesas Totais",
    "expenses.stats.recurring": "Recorrentes",
    "expenses.stats.categories": "Categorias",
    "expenses.stats.yearly": "Total Anual",
    "expenses.controls.view.calendar": "Calendário",
    "expenses.controls.view.list": "Lista",
    "expenses.controls.filter.all": "Todas Categorias",
    "expenses.form.placeholder.name": "ex: Aluguel, Mercado, Gasolina",
    "expenses.form.paymentMethod": "Formato de Pagamento",
    "expenses.form.paymentMethod.pix": "PIX",
    "expenses.form.paymentMethod.credit_card": "Cartão de Crédito",
    "expenses.form.paymentMethod.debit_card": "Cartão de Débito",
    "expenses.form.paymentMethod.cash": "Dinheiro",
    "expenses.form.creditCardAccount": "Conta do Cartão",
    "expenses.form.creditCardAccount.inter": "Inter",
    "expenses.form.creditCardAccount.xp": "XP",
    "expenses.form.purchaseDate": "Data da Compra",
    "expenses.form.purchaseDateHelper": "Quando você realizou esta compra?",
    "expenses.form.autoCalculatedDue": "Vencimento calculado conforme fechamento da fatura.",
    "expenses.list.active": "Despesa ativa",
    "expenses.legend": "Legenda de Tipos:",
    "expenses.type.oneTime": "Despesas únicas",
    "expenses.type.recurring": "Despesas recorrentes",
    "expenses.type.installment": "Despesas parceladas",
    "expenses.type.oneTimeLabel": "Única",
    "expenses.type.recurringLabel": "Recorrente",
    "expenses.type.installmentLabel": "Parcelado ({{months}} meses)",
    "expenses.noExpensesMonth": "Sem despesas neste mês",
    "expenses.monthlyEquivalent": "Equivalente Mensal",

    // Forecast
    "forecast.title": "Previsão Financeira",
    "forecast.projection": "Projeção Financeira",
    "forecast.months": "Meses para Prever",
    "forecast.startingBalance": "Saldo Inicial",
    "forecast.projectedBalance": "Saldo Projetado",
    "forecast.chart": "Gráfico de Previsão",
    "forecast.pageTitle": "Previsão Financeira",
    "forecast.pageSubtitle": "Projeções financeiras baseadas em sua renda atual, despesas e objetivos. Escolha sua data de início e período de previsão.",
    "forecast.period": "Período de previsão",
    "forecast.recalculating": "Recalculando...",
    "forecast.forecastPeriod": "Período de Previsão",
    "forecast.conservativeMode": "Modo Conservador",
    "forecast.includeGoals": "Incluir Objetivos",
    "forecast.reset": "Redefinir",
    "forecast.recalculate": "Recalcular",
    "forecast.resetAll": "Redefinir Tudo",
    "forecast.now": "Agora",
    "forecast.finalBalance": "Saldo Final",
    "forecast.totalIncome": "Renda Total",
    "forecast.totalExpenses": "Despesas Totais",
    "forecast.totalGoalContributions": "Contribuições para Objetivos",
    "forecast.afterMonths": "Após {months} meses",

    // Frequency
    "frequency.daily": "Diário",
    "frequency.weekly": "Semanal",
    "frequency.biweekly": "Quinzenal",
    "frequency.monthly": "Mensal",
    "frequency.quarterly": "Trimestral",
    "frequency.yearly": "Anual",
    "frequency.one_time": "Único",
    "forecast.avgMonth": "Média: {{amount}}/mês",
    "forecast.towardGoals": "Para seus objetivos",
    "forecast.details": "Detalhes da Previsão",
    "forecast.view.table": "Visão de Tabela",
    "forecast.view.chart": "Visão de Gráfico",
    "forecast.view.goals": "Progresso dos Objetivos",
    "forecast.view.calendar": "Visão de Calendário",
    "forecast.table.month": "Mês",
    "forecast.table.income": "Renda",
    "forecast.table.expenses": "Despesas",
    "forecast.table.goals": "Objetivos",
    "forecast.table.netChange": "Mudança Líquida",
    "forecast.table.endingBalance": "Saldo Final",
    "forecast.chart.title": "Tendência de Saldo",
    "forecast.chart.low": "Mín",
    "forecast.chart.avgNet": "Méd Liq",
    "forecast.chart.high": "Máx",
    "forecast.chart.legend.positive": "Saldo Positivo",
    "forecast.chart.legend.negative": "Saldo Negativo",
    "forecast.chart.legend.zero": "Linha Zero",
    "forecast.goals.title": "Projeções de Progresso de Metas",
    "forecast.goals.progressText": "{{current}} de {{target}}",
    "forecast.goals.onTrack": "No Prazo",
    "forecast.goals.behind": "Atrasado",
    "forecast.goals.estimatedCompletion": "Conclusão estimada",
    "forecast.goals.noActive": "Sem metas ativas para rastrear",
    "forecast.calendar.title": "Calendário de Previsão Mensal",
    "forecast.calendar.viewDetails": "Ver Detalhes",
    "forecast.calendar.items": "itens",
    "forecast.calendar.noData": "Nenhum dado de previsão disponível. Configure suas definições acima.",
    "forecast.warning.cashFlow": "Alerta de Fluxo de Caixa",
    "forecast.warning.negativeBalance": "Sua previsão mostra {{months}} meses com saldo negativo. Considere ajustar suas despesas ou aumentar a renda.",
    "forecast.resetModal.title": "Redefinir Configuração de Previsão",
    "forecast.resetModal.content": "Tem certeza que deseja redefinir todas as configurações de previsão para o padrão? Isso restaurará o saldo inicial para o saldo atual, redefinirá a data de início para o mês atual e restaurará outras configurações.",
    "forecast.resetModal.resetting": "Redefinindo...",
    "forecast.title.resetCurrent": "Redefinir para saldo atual",
    "forecast.title.recalculate": "Recalcular previsão",
    "forecast.title.resetAll": "Redefinir todas as configurações para o padrão",
    "forecast.title.selectStart": "Selecionar mês de início da previsão",
    "forecast.title.resetMonth": "Redefinir para o mês atual",
    "forecast.title.netChange": "Mudança líquida: {{amount}}",

    // Import/Export
    "importExport.title": "Importar / Exportar Dados",
    "importExport.exportDescription": "Baixe seus dados financeiros como um arquivo JSON.",
    "importExport.importDescription": "Carregue um arquivo JSON exportado anteriormente para restaurar seus dados.",
    "importExport.exportButton": "Exportar Dados",
    "importExport.importButton": "Importar Dados",
    "importExport.success": "Dados importados com sucesso!",
    "importExport.error": "Erro ao importar dados. Por favor, verifique o formato do arquivo.",

    // AI
    "ai.askAdvisor": "Consultar IA",
    "ai.analyzing": "Analisando suas finanças...",
    "ai.suggestion": "Sugestão",
    "ai.insight": "Insight",
    "ai.button.assistant": "IA Assistente",
    "ai.button.ask": "Perguntar à IA",
    "ai.button.setup": "Configurar IA",
    "ai.setup.title": "Recursos de IA Não Configurados",
    "ai.setup.desc": "Para usar a análise financeira com IA, você precisa configurar suas chaves de API.",
    "ai.setup.instructions": "Instruções de Configuração:",
    "ai.mode.prompt.title": "Modo Copiar e Colar",
    "ai.mode.prompt.desc": "Geraremos prompts otimizados que você pode copiar e colar no seu assistente de IA favorito (ChatGPT, Claude, Gemini, etc.) para obter conselhos financeiros personalizados.",
    "ai.tab.quick": "⚡ Análise Rápida",
    "ai.tab.custom": "💭 Pergunta Personalizada",
    "ai.custom.label": "Faça sua pergunta financeira",
    "ai.custom.placeholder": "ex: 'Devo priorizar pagar dívidas ou investir?' ou 'Como posso pagar minhas férias em 2 anos?'",
    "ai.custom.button.generate": "Gerar Prompt",
    "ai.custom.button.analyze": "Obter Análise da IA",
    "ai.result.analysis": "Análise",
    "ai.result.recommendations": "Recomendações",
    "ai.result.nextSteps": "Próximos Passos",
    "ai.result.failed": "Análise Falhou",
    "ai.result.tryAgain": "Tentar Novamente",
    "ai.model": "Modelo de IA",
    "ai.modal.title.prompt": "Assistente Financeiro IA",
    "ai.modal.title.advisor": "Consultor Financeiro IA",
    "ai.modal.subtitle.prompt": "Gere prompts para seu assistente de IA favorito",
    "ai.modal.subtitle.advisor": "Obtenha insights personalizados sobre suas finanças",
    "ai.footer.prompt": "📋 Seus dados permanecem privados - prompts são gerados localmente",
    "ai.footer.api": "🔒 Seus dados financeiros são analisados de forma segura e privada",
    "ai.close": "Fechar",
    "ai.clear": "Limpar",
    "ai.generatedPrompt": "Prompt Gerado",
    "ai.copied": "Copiado!",
    "ai.copy": "Copiar Prompt",
    "ai.howToUse": "Como usar este prompt:",
    "ai.step1": "Copie o prompt acima usando o botão \"Copiar Prompt\"",
    "ai.step2": "Abra seu assistente de IA favorito (ChatGPT, Claude, Gemini, etc.)",
    "ai.step3": "Cole o prompt e envie",
    "ai.step4": "Receba conselhos financeiros personalizados baseados em seus dados!",


    // Theme
    "theme.toggle.light": "Alternar para modo claro",
    "theme.toggle.dark": "Alternar para modo escuro",

    // Charts - Expenses
    "charts.expenses.title": "Divisão de Despesas",
    "charts.expenses.subtitle": "Analise sua distribuição de gastos por categorias",
    "charts.expenses.includeInactive": "Incluir Inativos",
    "charts.expenses.view.pie": "Pizza",
    "charts.expenses.view.donut": "Rosca",
    "charts.expenses.view.bar": "Barra",
    "charts.expenses.view.treemap": "Árvore",
    "charts.expenses.categories": "Categorias",
    "charts.expenses.count": "despesas",
    "charts.expenses.details": "Detalhes",
    "charts.expenses.original": "Original",
    "charts.expenses.monthly": "Mensal",
    "charts.expenses.totalMonthly": "Total Mensal",
    "charts.expenses.totalExpenses": "Total Despesas",
    "charts.expenses.avgPerCategory": "Média por Categoria",
    "charts.expenses.noData.title": "Sem Despesas Ainda",
    "charts.expenses.noData.desc": "Adicione algumas despesas para ver sua divisão por categorias",
    "charts.expenses.help": "💡 Clique nos segmentos ou na lista para detalhar • Mude a visualização",

    // Charts - Goals
    "charts.goals.title": "Progresso das Metas",
    "charts.goals.subtitle": "Monitore suas metas financeiras e previsões",
    "charts.goals.activeOnly": "Apenas Ativos",
    "charts.goals.view.progress": "Progresso",
    "charts.goals.view.timeline": "Linha do Tempo",
    "charts.goals.view.allocation": "Alocação",
    "charts.goals.totalGoals": "Total de Metas",
    "charts.goals.onTrack": "No Caminho",
    "charts.goals.totalSaved": "Total Salvo",
    "charts.goals.monthlyAllocation": "Alocação Mensal",
    "charts.goals.noData.title": "Sem Metas Ainda",
    "charts.goals.noData.desc": "Crie sua primeira meta financeira para ver o progresso",
    "charts.goals.help": "💡 Clique nas metas para informações detalhadas • Use os modos de visualização",
    "charts.goals.status.onTrack": "No Caminho",
    "charts.goals.status.behind": "Atrasado",
    "charts.goals.tooltip.progress": "Progresso",
    "charts.goals.tooltip.current": "Atual",
    "charts.goals.tooltip.target": "Alvo",
    "charts.goals.tooltip.remaining": "Restante",
    "charts.goals.tooltip.status": "Status",
    "charts.goals.tooltip.completion": "Conclusão",

    // Charts - Income vs Expenses
    "charts.incomeVsExpenses.title": "Tendência: Renda vs Despesas",
    "charts.incomeVsExpenses.subtitle": "Acompanhe seu fluxo financeiro ao longo do tempo",
    "charts.incomeVsExpenses.period": "Período",
    "charts.incomeVsExpenses.showProjection": "Mostrar Projeção",
    "charts.incomeVsExpenses.months": "Meses",
    "charts.incomeVsExpenses.avgIncome": "Renda Média Mensal",
    "charts.incomeVsExpenses.avgExpenses": "Despesa Média Mensal",
    "charts.incomeVsExpenses.avgNet": "Renda Líquida Média",
    "charts.incomeVsExpenses.help": "💡 Clique na legenda para focar • Passe o mouse para detalhes",
    "charts.incomeVsExpenses.series.income": "Renda",
    "charts.incomeVsExpenses.series.expenses": "Despesas",
    "charts.incomeVsExpenses.series.netIncome": "Renda Líquida",
    "charts.incomeVsExpenses.tooltip.income": "Renda",
    "charts.incomeVsExpenses.tooltip.expenses": "Despesas",
    "charts.incomeVsExpenses.tooltip.net": "Líquido",
    "charts.incomeVsExpenses.tooltip.surplus": "Superávit",
    "charts.incomeVsExpenses.tooltip.deficit": "Déficit",


    // Currencies
    "currency.selector.title": "Selecionar Moeda",
    "currency.selector.label": "Selecionar moeda",
    "currency.selector.buttonTitle": "Moeda atual: {{name}}",

    // Languages
    "language.selector.title": "Selecionar Idioma",
    "language.selector.label": "Selecionar idioma",

    // Months
    "month.january": "Janeiro",
    "month.february": "Fevereiro",
    "month.march": "Março",
    "month.april": "Abril",
    "month.may": "Maio",
    "month.june": "Junho",
    "month.july": "Julho",
    "month.august": "Agosto",
    "month.september": "Setembro",
    "month.october": "Outubro",
    "month.november": "Novembro",
    "month.december": "Dezembro",
    "goalPlan.title": "Planejamento de Metas",
    "goalPlan.subtitle": "Planeje e acompanhe suas alocações mensais de metas com projeções detalhadas e insights",
    "goalPlan.summary.totalSuggestions": "Total de Sugestões",
    "goalPlan.summary.potentialImpact": "Impacto Potencial",
    "goalPlan.summary.perMonth": "Por mês, se tudo for implementado",
    "goalPlan.summary.actionableItems": "Itens Acionáveis",
    "goalPlan.schedule.title": "Cronograma de Alocação Mensal de Metas",
    "goalPlan.schedule.subtitle": "Detalhamento mês a mês das alocações recomendadas com base na sua previsão financeira",
    "goalPlan.schedule.showAllocation": "Mostrar Alocação",
    "goalPlan.schedule.export": "Exportar CSV",
    "goalPlan.schedule.view.calendar": "Calendário",
    "goalPlan.schedule.view.table": "Tabela",
    "goalPlan.schedule.view.chart": "Gráfico",
    "goalPlan.stats.monthlyAvg": "Média Mensal Total",
    "goalPlan.stats.onTrack": "Metas no Caminho",
    "goalPlan.stats.surplusMonths": "Meses com Superávit",
    "goalPlan.stats.peakAllocation": "Alocação Máxima",
    "goalPlan.empty.title": "Sem Metas Ainda",
    "goalPlan.empty.desc": "Adicione algumas metas financeiras para ver seu cronograma de alocação mensal personalizado",
    "goalPlan.empty.button": "Adicionar Metas",
    "goalPlan.calendar.total": "Total: {{amount}}",
    "goalPlan.calendar.surplus": "{{amount}} de superávit disponível",
    "goalPlan.calendar.surplusRemaining": "{{amount}} de superávit restante",
    "goalPlan.calendar.noAllocations": "Sem alocações",
    "goalPlan.table.month": "Mês",
    "goalPlan.table.allocations": "Alocações de Metas",
    "goalPlan.table.total": "Alocação Total",
    "goalPlan.table.surplus": "Superávit Restante",
    "goalPlan.table.guidance": "Orientação",
    "goalPlan.table.goalsFunded": "Metas financiadas",
    "goalPlan.table.surplusAvailable": "Superávit disponível",
    "goalPlan.table.noSurplus": "Sem superávit",
    "goalPlan.chart.trends": "Tendências de Alocação Mensal",
    "goalPlan.chart.legend.allocations": "Alocações de Metas",
    "goalPlan.chart.legend.surplus": "Superávit Disponível",
    "goalPlan.chart.distribution": "Distribuição do Progresso das Metas",
    "goalPlan.chart.openEnded": "Em aberto • {{amount}}",
    "goalPlan.projections.title": "Projeções de Progresso das Metas",
    "goalPlan.projections.subtitle": "Veja como suas metas progredirão com base no plano de alocação atual",
    "goalPlan.projections.forecastPeriod": "Período de Previsão",
    "goalPlan.projections.months": "{{count}} meses",
    "goalPlan.projections.current": "Atual:",
    "goalPlan.projections.projected": "Projetado:",
    "goalPlan.projections.target": "Alvo:",
    "goalPlan.projections.willComplete": "Será Concluído",
    "goalPlan.projections.onTrack": "No Caminho",
    "goalPlan.projections.behind": "Atrasado",
    "goalPlan.projections.projectedLabel": "{{percent}} projetado",
    "goalPlan.projections.monthlyAllocation": "Alocação Mensal",
    "goalPlan.projections.estimatedCompletion": "Conclusão Estimada",
    "goalPlan.projections.notDetermined": "Não determinado",
    "goalPlan.projections.remainingAmount": "Valor Restante",
    "goalPlan.projections.warning": "Esta meta pode não atingir o alvo a tempo.",
    "goalPlan.projections.warningDesc": "Considere aumentar a alocação mensal ou ajustar a data alvo.",
    "goalPlan.projections.success": "Esta meta será concluída dentro do período de previsão!",
    "goalPlan.projections.summary.onTrack": "Metas no Caminho",
    "goalPlan.projections.summary.willComplete": "Será Concluído",
    "goalPlan.projections.summary.totalAllocation": "Alocação Mensal Total",
    "goalPlan.tools.title": "Ferramentas de Planejamento",
    "goalPlan.tools.subtitle": "Experimente diferentes cenários de alocação e obtenha sugestões de otimização",
    "goalPlan.optimizer.title": "Otimizador de Alocação Inteligente",
    "goalPlan.optimizer.current": "Alocação Atual",
    "goalPlan.optimizer.suggestions": "Sugestões de Otimização",
    "goalPlan.optimizer.rebalance.title": "Reequilibrar Alocações",
    "goalPlan.optimizer.rebalance.desc": "Considere reduzir a alocação para {{early}} e aumentar para {{late}}",
    "goalPlan.optimizer.rebalance.impact": "Pode melhorar o cronograma geral de conclusão",
    "goalPlan.optimizer.surplus.title": "Usar Superávit Disponível",
    "goalPlan.optimizer.surplus.desc": "Você tem {{amount}} em superávit que poderia acelerar a conclusão das metas",
    "goalPlan.optimizer.surplus.impact": "Pode trazer metas atrasadas de volta aos trilhos",
    "goalPlan.optimizer.timeline.title": "Otimização do Cronograma",
    "goalPlan.optimizer.timeline.desc": "Considere ajustar os prazos das metas para criar alocações mensais mais equilibradas",
    "goalPlan.optimizer.timeline.impact": "Pode reduzir meses de pico de alocação e melhorar o fluxo de caixa",
    "goalPlan.scenarios.title": "Cenários \"E Se\"",
    "goalPlan.scenarios.budget.title": "+20% Orçamento",
    "goalPlan.scenarios.budget.desc": "E se você aumentasse a poupança mensal em 20%?",
    "goalPlan.scenarios.budget.newAvg": "Nova média mensal:",
    "goalPlan.scenarios.budget.reduction": "Redução estimada de tempo:",
    "goalPlan.scenarios.budget.impact": "Metas poderiam ser concluídas {{speed}} mais rápido",
    "goalPlan.scenarios.budget.impactHigh": "significativamente",
    "goalPlan.scenarios.budget.impactMod": "moderadamente",
    "goalPlan.scenarios.extension.title": "Extensão de +6 Meses",
    "goalPlan.scenarios.extension.desc": "E se você estendesse os prazos das metas em 6 meses?",
    "goalPlan.scenarios.extension.reduced": "Mensal reduzido:",
    "goalPlan.scenarios.extension.savings": "Economia mensal:",
    "goalPlan.scenarios.extension.impact": "Mais folga no orçamento mensal",
    "goalPlan.scenarios.priority.title": "Reordenar Prioridades",
    "goalPlan.scenarios.priority.desc": "E se você focasse primeiro nas metas de maior prioridade?",
    "goalPlan.scenarios.priority.highGoals": "Metas de alta prioridade:",
    "goalPlan.scenarios.priority.strategy": "Estratégia de foco:",
    "goalPlan.scenarios.priority.strategyVal": "Conclusão sequencial",
    "goalPlan.scenarios.priority.impact": "Conclua metas importantes mais rápido, outras depois",
    "goalPlan.quickActions.title": "Ações Rápidas de Planejamento",
    "goalPlan.quickActions.export": "Exportar Plano",
    "goalPlan.quickActions.exportDesc": "Baixe seu cronograma completo de alocação",
    "goalPlan.quickActions.adjust": "Ajustar Metas",
    "goalPlan.quickActions.adjustDesc": "Modifique alvos, prazos ou prioridades",
    "goalPlan.quickActions.settings": "Configurações de Previsão",
    "goalPlan.quickActions.settingsDesc": "Ajuste o cronograma e parâmetros de previsão",
    "goalPlan.quickActions.backup": "Backup do Plano",
    "goalPlan.quickActions.backupDesc": "Salve ou restaure seu plano financeiro",
    "goalPlan.tips.title": "Como Usar Estas Sugestões",
    "goalPlan.tips.priority": "Níveis de Prioridade",
    "goalPlan.tips.priority.critical": "Crítico: Aborde imediatamente para evitar estresse financeiro",
    "goalPlan.tips.priority.high": "Alto: Importante para a saúde financeira a longo prazo",
    "goalPlan.tips.priority.medium": "Médio: Boas oportunidades de melhoria",
    "goalPlan.tips.priority.low": "Baixo: Otimizações desejáveis",
    "goalPlan.tips.categories": "Categorias",
    "goalPlan.tips.categories.income": "Renda: Maneiras de aumentar seus ganhos",
    "goalPlan.tips.categories.expense": "Despesa: Oportunidades para reduzir gastos",
    "goalPlan.tips.categories.goal": "Meta: Ajuda para alcançar objetivos financeiros",
    "goalPlan.tips.categories.general": "Geral: Melhorias gerais na saúde financeira",
  },
};

function getTranslations(language: LanguageCode): Record<string, string> {
  return translations[language];
}
